# Generated by Django 6.0.5 on 2026-05-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_hi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='details_ar',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='product',
            name='details_en',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='product',
            name='details_hi',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='product',
            name='details_ru',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='product',
            name='details_uz',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
